/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShipmentStatus = IDL.Variant({
  'orderPlaced' : IDL.Null,
  'inTransit' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const Shipment = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Float64,
  'status' : ShipmentStatus,
  'trackingNumber' : IDL.Text,
  'destination' : IDL.Text,
  'deliveryPersonRating' : IDL.Float64,
  'contents' : IDL.Text,
  'createdAt' : Time,
  'origin' : IDL.Text,
  'updatedAt' : Time,
  'deliveryPersonName' : IDL.Text,
  'deliveryPersonVehicle' : IDL.Text,
  'dimensions' : IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64),
  'estimatedArrival' : Time,
});
export const ActivityEvent = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addActivityEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createShipment' : IDL.Func([Shipment], [], []),
  'getActivity' : IDL.Func([IDL.Text], [IDL.Vec(ActivityEvent)], ['query']),
  'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getShipmentByTracking' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Shipment)],
      ['query'],
    ),
  'seedDemoData' : IDL.Func([], [], []),
  'updateShipmentStatus' : IDL.Func([IDL.Text, ShipmentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShipmentStatus = IDL.Variant({
    'orderPlaced' : IDL.Null,
    'inTransit' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const Shipment = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Float64,
    'status' : ShipmentStatus,
    'trackingNumber' : IDL.Text,
    'destination' : IDL.Text,
    'deliveryPersonRating' : IDL.Float64,
    'contents' : IDL.Text,
    'createdAt' : Time,
    'origin' : IDL.Text,
    'updatedAt' : Time,
    'deliveryPersonName' : IDL.Text,
    'deliveryPersonVehicle' : IDL.Text,
    'dimensions' : IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64),
    'estimatedArrival' : Time,
  });
  const ActivityEvent = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addActivityEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createShipment' : IDL.Func([Shipment], [], []),
    'getActivity' : IDL.Func([IDL.Text], [IDL.Vec(ActivityEvent)], ['query']),
    'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getShipmentByTracking' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Shipment)],
        ['query'],
      ),
    'seedDemoData' : IDL.Func([], [], []),
    'updateShipmentStatus' : IDL.Func([IDL.Text, ShipmentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };