/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent { 'message' : string, 'timestamp' : Time }
export interface Shipment {
  'id' : bigint,
  'weight' : number,
  'status' : ShipmentStatus,
  'trackingNumber' : string,
  'destination' : string,
  'deliveryPersonRating' : number,
  'contents' : string,
  'createdAt' : Time,
  'origin' : string,
  'updatedAt' : Time,
  'deliveryPersonName' : string,
  'deliveryPersonVehicle' : string,
  'dimensions' : [number, number, number],
  'estimatedArrival' : Time,
}
export type ShipmentStatus = { 'orderPlaced' : null } |
  { 'inTransit' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null };
export type Time = bigint;
export interface _SERVICE {
  'addActivityEntry' : ActorMethod<[string, string], undefined>,
  'createShipment' : ActorMethod<[Shipment], undefined>,
  'getActivity' : ActorMethod<[string], Array<ActivityEvent>>,
  'getAllShipments' : ActorMethod<[], Array<Shipment>>,
  'getShipmentByTracking' : ActorMethod<[string], [] | [Shipment]>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'updateShipmentStatus' : ActorMethod<[string, ShipmentStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];