/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ActivityEvent {
    message: string;
    timestamp: Time;
}
export interface Shipment {
    id: bigint;
    weight: number;
    status: ShipmentStatus;
    trackingNumber: string;
    destination: string;
    deliveryPersonRating: number;
    contents: string;
    createdAt: Time;
    origin: string;
    updatedAt: Time;
    deliveryPersonName: string;
    deliveryPersonVehicle: string;
    dimensions: [number, number, number];
    estimatedArrival: Time;
}
export enum ShipmentStatus {
    orderPlaced = "orderPlaced",
    inTransit = "inTransit",
    pickedUp = "pickedUp",
    delivered = "delivered"
}
export interface backendInterface {
    addActivityEntry(trackingNumber: string, message: string): Promise<void>;
    createShipment(shipment: Shipment): Promise<void>;
    getActivity(trackingNumber: string): Promise<Array<ActivityEvent>>;
    getAllShipments(): Promise<Array<Shipment>>;
    getShipmentByTracking(trackingNumber: string): Promise<Shipment | null>;
    seedDemoData(): Promise<void>;
    updateShipmentStatus(trackingNumber: string, newStatus: ShipmentStatus): Promise<void>;
}
import type { Shipment as _Shipment, ShipmentStatus as _ShipmentStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivityEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivityEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivityEntry(arg0, arg1);
            return result;
        }
    }
    async createShipment(arg0: Shipment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createShipment(to_candid_Shipment_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShipment(to_candid_Shipment_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getActivity(arg0: string): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return result;
        }
    }
    async getAllShipments(): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShipments();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShipments();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShipmentByTracking(arg0: string): Promise<Shipment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShipmentByTracking(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShipmentByTracking(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async updateShipmentStatus(arg0: string, arg1: ShipmentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShipmentStatus(arg0, to_candid_ShipmentStatus_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShipmentStatus(arg0, to_candid_ShipmentStatus_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ShipmentStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShipmentStatus): ShipmentStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Shipment_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shipment): Shipment {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shipment]): Shipment | null {
    return value.length === 0 ? null : from_candid_Shipment_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    weight: number;
    status: _ShipmentStatus;
    trackingNumber: string;
    destination: string;
    deliveryPersonRating: number;
    contents: string;
    createdAt: _Time;
    origin: string;
    updatedAt: _Time;
    deliveryPersonName: string;
    deliveryPersonVehicle: string;
    dimensions: [number, number, number];
    estimatedArrival: _Time;
}): {
    id: bigint;
    weight: number;
    status: ShipmentStatus;
    trackingNumber: string;
    destination: string;
    deliveryPersonRating: number;
    contents: string;
    createdAt: Time;
    origin: string;
    updatedAt: Time;
    deliveryPersonName: string;
    deliveryPersonVehicle: string;
    dimensions: [number, number, number];
    estimatedArrival: Time;
} {
    return {
        id: value.id,
        weight: value.weight,
        status: from_candid_ShipmentStatus_n8(_uploadFile, _downloadFile, value.status),
        trackingNumber: value.trackingNumber,
        destination: value.destination,
        deliveryPersonRating: value.deliveryPersonRating,
        contents: value.contents,
        createdAt: value.createdAt,
        origin: value.origin,
        updatedAt: value.updatedAt,
        deliveryPersonName: value.deliveryPersonName,
        deliveryPersonVehicle: value.deliveryPersonVehicle,
        dimensions: value.dimensions,
        estimatedArrival: value.estimatedArrival
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orderPlaced: null;
} | {
    inTransit: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
}): ShipmentStatus {
    return "orderPlaced" in value ? ShipmentStatus.orderPlaced : "inTransit" in value ? ShipmentStatus.inTransit : "pickedUp" in value ? ShipmentStatus.pickedUp : "delivered" in value ? ShipmentStatus.delivered : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shipment>): Array<Shipment> {
    return value.map((x)=>from_candid_Shipment_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ShipmentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): _ShipmentStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Shipment_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Shipment): _Shipment {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    weight: number;
    status: ShipmentStatus;
    trackingNumber: string;
    destination: string;
    deliveryPersonRating: number;
    contents: string;
    createdAt: Time;
    origin: string;
    updatedAt: Time;
    deliveryPersonName: string;
    deliveryPersonVehicle: string;
    dimensions: [number, number, number];
    estimatedArrival: Time;
}): {
    id: bigint;
    weight: number;
    status: _ShipmentStatus;
    trackingNumber: string;
    destination: string;
    deliveryPersonRating: number;
    contents: string;
    createdAt: _Time;
    origin: string;
    updatedAt: _Time;
    deliveryPersonName: string;
    deliveryPersonVehicle: string;
    dimensions: [number, number, number];
    estimatedArrival: _Time;
} {
    return {
        id: value.id,
        weight: value.weight,
        status: to_candid_ShipmentStatus_n3(_uploadFile, _downloadFile, value.status),
        trackingNumber: value.trackingNumber,
        destination: value.destination,
        deliveryPersonRating: value.deliveryPersonRating,
        contents: value.contents,
        createdAt: value.createdAt,
        origin: value.origin,
        updatedAt: value.updatedAt,
        deliveryPersonName: value.deliveryPersonName,
        deliveryPersonVehicle: value.deliveryPersonVehicle,
        dimensions: value.dimensions,
        estimatedArrival: value.estimatedArrival
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): {
    orderPlaced: null;
} | {
    inTransit: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} {
    return value == ShipmentStatus.orderPlaced ? {
        orderPlaced: null
    } : value == ShipmentStatus.inTransit ? {
        inTransit: null
    } : value == ShipmentStatus.pickedUp ? {
        pickedUp: null
    } : value == ShipmentStatus.delivered ? {
        delivered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
